export const authConstant = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",
};

export const userConstant = {
  GET_REALTIMEUSERS: "GET_REALTIMEUSERS",
  GET_REALTIME_MESSAGES: "GET_REALTIMEMESSAGES",
};
